name: RandomOneBlockPlugin
version: '${project.version}'
main: org.julapalula.randomoneblock.core.ROBPlugin
api-version: '1.21'
load: STARTUP
description: Random item every minute!
author: JULAPALULA
commands:
  lot:
    description: Main command for OneBlockPlugin
    usage: /lot <subcommand> [arguments]