name: OneBlockPlugin
version: '${project.version}'
main: org.julapalula.oneblockplugin.core.OneBlockPlugin
api-version: '1.21'
load: STARTUP
description: Test plugin
author: JULAPALULA
commands:
  lot:
    description: Main command for OneBlockPlugin
    usage: /lot <subcommand> [arguments]